-- Spotify Wrapper Database Setup Script
-- Run this script to set up the initial database structure

-- Create database
CREATE DATABASE IF NOT EXISTS spotify_wrapper;
USE spotify_wrapper;

-- Create user table (will be auto-generated by JPA, but provided here for reference)
CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    spotify_user_id VARCHAR(255) UNIQUE NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    access_token TEXT NOT NULL,
    refresh_token TEXT NOT NULL,
    token_expires_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    INDEX idx_spotify_user_id (spotify_user_id),
    INDEX idx_token_expires_at (token_expires_at)
);

-- Create a database user for the application (optional)
-- Replace 'your_password' with a secure password
-- CREATE USER IF NOT EXISTS 'spotify_user'@'localhost' IDENTIFIED BY 'your_password';
-- GRANT SELECT, INSERT, UPDATE, DELETE ON spotify_wrapper.* TO 'spotify_user'@'localhost';
-- FLUSH PRIVILEGES;

-- Display table structure
DESCRIBE users;
